/**
 * Demo notifications — replace with API / Supabase when wired.
 * Each item maps to a welfare area so the hub can filter and deep-link.
 */
import type {
  WelfareNotificationCategory,
  NotificationItem,
  NotificationSection,
  NotificationStatusType,
} from './types';

export const NOTIFICATION_CATEGORY_LABEL: Record<WelfareNotificationCategory, string> = {
  health: 'Health',
  discipline: 'Discipline',
  scholarships: 'Scholarships',
  referrals: 'Referrals',
  campus: 'Campus',
};

/**
 * Full set of discipline-related notification templates.
 * Sections: today (3 items), yesterday (4 items), then last7 / last30 for the rest.
 */
export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  // ───────────────────────── TODAY ─────────────────────────
  {
    id: 'nte-urgent',
    category: 'discipline',
    title: 'NTE Deadline Reminder',
    body: 'This is urgent: Your response to the Notice to Explain is due in 1 hour. Please submit your explanation now to prevent escalation.',
    timeLabel: '1h ago',
    read: false,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'nte-issued',
    category: 'discipline',
    title: 'NTE Issued',
    body: 'You have received a Notice to Explain regarding an incident. Please submit your explanation by April 25, 2026 to avoid any issues.',
    timeLabel: '3h ago',
    read: false,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'nte-submitted',
    category: 'discipline',
    title: 'NTE Response Submitted',
    body: 'Thank you! Your explanation for the Notice to Explain has been submitted successfully. The disciplinary committee will review it.',
    timeLabel: '6h ago',
    read: false,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'success',
  },

  // ─────────────────────── YESTERDAY ───────────────────────
  {
    id: 'nte-deadline-tomorrow',
    category: 'discipline',
    title: 'NTE Deadline Reminder',
    body: 'Your response to the Notice to Explain is due tomorrow. Please make sure to submit your explanation before the deadline.',
    timeLabel: 'Yesterday',
    read: false,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'nte-status',
    category: 'discipline',
    title: 'NTE Status',
    body: 'Your response to the Notice to Explain has been received. Your explanation is currently under review.',
    timeLabel: 'Yesterday',
    read: true,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'info',
  },
  {
    id: 'case-hearing-reminder',
    category: 'discipline',
    title: 'Case Hearing Reminder',
    body: 'Just a reminder: Your hearing is scheduled for tomorrow at 10:00 AM. Please be on time.',
    timeLabel: 'Yesterday',
    read: false,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'sanction-final-reminder',
    category: 'discipline',
    title: 'Sanction Deadline Reminder',
    body: 'Final reminder: Your sanction requirements are due tomorrow. Please complete them now to avoid escalation.',
    timeLabel: 'Yesterday',
    read: true,
    href: '/discipline-office/my-sanctions',
    source: 'Discipline Office',
    notificationType: 'error',
  },

  // ───────────────────────── LAST 7 DAYS / LAST 30 DAYS ─────────────────────────
  // NTE
  {
    id: 'nte-resolved',
    category: 'discipline',
    title: 'NTE Resolved',
    body: 'Good news! The Notice to Explain has been resolved. No further action is required from you.',
    timeLabel: '2 days ago',
    read: true,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'success',
  },
  {
    id: 'nte-escalated',
    category: 'discipline',
    title: 'NTE Escalated',
    body: 'The Notice to Explain has been escalated to a case because no response was received. Please contact the Discipline Office immediately.',
    timeLabel: '3 days ago',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'error',
  },

  // Case
  {
    id: 'case-opened',
    category: 'discipline',
    title: 'Case Opened',
    body: 'A disciplinary case has been opened regarding your record. Please check the Discipline Office screen for more details.',
    timeLabel: '4 days ago',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'case-status-update',
    category: 'discipline',
    title: 'Case Status Update',
    body: 'There is a status update for your disciplinary case. Please review the latest information in the Discipline Office.',
    timeLabel: '5 days ago',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'info',
  },
  {
    id: 'case-hearing-scheduled',
    category: 'discipline',
    title: 'Case Hearing Scheduled',
    body: 'A hearing has been scheduled for your case on April 28, 2026 at 10:00 AM. Please make sure to attend.',
    timeLabel: '6 days ago',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'info',
  },
  {
    id: 'case-resolved',
    category: 'discipline',
    title: 'Case Resolved',
    body: 'Your disciplinary case has been resolved. The verdict is: Written Reprimand. Please review the details.',
    timeLabel: 'April 22, 2026',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'success',
  },
  {
    id: 'case-closed',
    category: 'discipline',
    title: 'Case Closed',
    body: 'Your disciplinary case has been closed. No further action is required.',
    timeLabel: 'April 20, 2026',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'success',
  },

  // Sanction
  {
    id: 'sanction-issued',
    category: 'discipline',
    title: 'Sanction Issued',
    body: 'A sanction has been assigned to you. Please complete the required actions by May 15, 2026.',
    timeLabel: 'April 18, 2026',
    read: true,
    href: '/discipline-office/my-sanctions',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'sanction-7day',
    category: 'discipline',
    title: 'Sanction Deadline Reminder',
    body: 'Reminder: Your sanction requirements are due in 7 days. Please complete them to avoid any penalties.',
    timeLabel: 'April 15, 2026',
    read: true,
    href: '/discipline-office/my-sanctions',
    source: 'Discipline Office',
    notificationType: 'info',
  },
  {
    id: 'sanction-3day',
    category: 'discipline',
    title: 'Sanction Deadline Reminder',
    body: 'This is important: Your sanction requirements are due in 3 days. Please complete them as soon as possible.',
    timeLabel: 'April 14, 2026',
    read: true,
    href: '/discipline-office/my-sanctions',
    source: 'Discipline Office',
    notificationType: 'error',
  },
  {
    id: 'sanction-completed',
    category: 'discipline',
    title: 'Sanction Completed',
    body: 'Congratulations! You have successfully completed your sanction requirements.',
    timeLabel: 'April 12, 2026',
    read: true,
    href: '/discipline-office/my-sanctions',
    source: 'Discipline Office',
    notificationType: 'success',
  },
  {
    id: 'sanction-extended',
    category: 'discipline',
    title: 'Sanction Extended',
    body: 'Your sanction deadline has been extended until May 30, 2026. Please contact the Discipline Office if you have any questions.',
    timeLabel: 'April 10, 2026',
    read: true,
    href: '/discipline-office/my-sanctions',
    source: 'Discipline Office',
    notificationType: 'info',
  },

  // General
  {
    id: 'clean-record',
    category: 'discipline',
    title: 'Clean Record Achievement',
    body: 'Great news! Your disciplinary record is now clean. Keep up the excellent work!',
    timeLabel: 'April 8, 2026',
    read: true,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'success',
  },
  {
    id: 'new-document',
    category: 'discipline',
    title: 'New Document Available',
    body: 'A new document has been added to your case. Please review it in the Discipline Office.',
    timeLabel: 'April 6, 2026',
    read: true,
    href: '/discipline-office/my-cases',
    source: 'Discipline Office',
    notificationType: 'info',
  },
  {
    id: 'system-maintenance',
    category: 'campus',
    title: 'System Maintenance',
    body: 'The Discipline Office system will be under maintenance on April 5, 2026 from 11:00 PM to 2:00 AM. You may experience temporary unavailability during this time.',
    timeLabel: 'April 4, 2026',
    read: true,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'info',
  },
  {
    id: 'contact-request',
    category: 'discipline',
    title: 'Contact Request',
    body: 'The Discipline Office would like to contact you regarding your case. Please check your email for more details.',
    timeLabel: 'April 2, 2026',
    read: true,
    href: '/discipline-office',
    source: 'Discipline Office',
    notificationType: 'info',
  },
];
