-- DO + SDAO shared welfare portal (single dashboard at /admin/do).
-- Example account: welfare_admin@gmail.com — create the user in Supabase Dashboard → Authentication,
-- not via the public CampusCare signup form.
--
-- After "Add user", set Raw User Metadata (example):
-- {
--   "first_name": "Welfare",
--   "last_name": "Admin",
--   "middle_initial": "",
--   "office": "discipline",
--   "role": "Admin",
--   "signup_office_raw": "discipline_super_admin"
-- }
-- Using "office": "development" with "signup_office_raw": "development_super_admin" is equivalent;
-- the app always opens /admin/do for both.
--
-- public.handle_new_user() creates the profiles row. If you need to fix an existing row:
-- update public.profiles
-- set office = 'discipline', role = 'Admin', account_status = 'approved', designation = null
-- where lower(email) = lower('welfare_admin@gmail.com');
--
-- ── Troubleshooting "Failed to create user" in Dashboard ─────────────────────
-- 1) Use exact metadata keys: first_name, last_name, middle_initial, office, role, designation (HSO only).
-- 2) "office" must be: health | discipline | development | guidance (lowercase), not "Discipline Office".
-- 3) For HSO, designation must be one of: nurse, physician, dentist, admin, queue_display, welfare_admin.
-- 4) Duplicate email: delete the existing auth user first or use another email.
-- 5) If the trigger errors, open Supabase → Database → Logs, or SQL: select * from auth.users order by created_at desc;
--    Apply latest migrations so handle_new_user matches (upsert + email coalesce): 20260601120000_handle_new_user_upsert_email.sql
