import type { Referral } from './types';

const ago = (ms: number) => new Date(Date.now() - ms);
const mins  = (n: number) => n * 60 * 1000;
const hours = (n: number) => n * 60 * mins(1);
const days  = (n: number) => n * 24 * hours(1);

export const MOCK_REFERRALS: Referral[] = [
  {
    id: '1',
    referralNumber: 'REF-2025-001',
    createdAt: ago(hours(2)),
    fromOffice: 'Health Services Clinic',
    toOffice: 'Counseling Office',
    category: 'Mental Health',
    reason: 'Student reported persistent anxiety and difficulty concentrating in class, requesting professional counseling support.',
    status: 'in_review',
    priority: 'normal',
    referredBy: 'Dr. Maria Santos',
    assignedTo: 'Ms. Ana Reyes',
    nextAppointment: 'Apr 21, 2025 · 10:00 AM',
  },
  {
    id: '2',
    referralNumber: 'REF-2025-002',
    createdAt: ago(mins(45)),
    fromOffice: 'Discipline Office',
    toOffice: 'Guidance Center',
    category: 'Bullying',
    reason: 'Student was involved in repeated verbal altercations with peers in the corridor. Immediate guidance intervention required.',
    status: 'pending',
    priority: 'urgent',
    referredBy: 'Prof. James Torres',
  },
  {
    id: '3',
    referralNumber: 'REF-2025-003',
    createdAt: ago(days(2)),
    fromOffice: 'Health Services Clinic',
    toOffice: 'Counseling Office',
    category: 'Family Issue',
    reason: 'Student experiencing home instability affecting academic performance and attendance.',
    status: 'scheduled',
    priority: 'normal',
    referredBy: 'Nurse Clara Lim',
    assignedTo: 'Dr. Kevin Ramos',
    nextAppointment: 'Apr 22, 2025 · 2:00 PM',
  },
  {
    id: '4',
    referralNumber: 'REF-2025-004',
    createdAt: ago(days(4)),
    fromOffice: 'Student Development & Affairs',
    toOffice: 'Counseling Office',
    category: 'Academic Concern',
    reason: 'Student at risk of failing two core subjects. Needs academic counseling and study plan intervention.',
    status: 'completed',
    priority: 'normal',
    referredBy: 'Mr. Paolo Cruz',
    assignedTo: 'Ms. Ana Reyes',
  },
  {
    id: '5',
    referralNumber: 'REF-2025-005',
    createdAt: ago(days(7)),
    fromOffice: 'Guidance Center',
    toOffice: 'Health Services Clinic',
    category: 'Physical Health',
    reason: 'Student complained of recurring headaches and fatigue during afternoon classes. Referred for medical evaluation.',
    status: 'completed',
    priority: 'normal',
    referredBy: 'Ms. Ana Reyes',
    assignedTo: 'Dr. Maria Santos',
  },
  {
    id: '6',
    referralNumber: 'REF-2025-006',
    createdAt: ago(mins(10)),
    fromOffice: 'Discipline Office',
    toOffice: 'Counseling Office',
    category: 'Behavioral',
    reason: 'Student exhibited disruptive behavior in multiple classes. Teacher reports suggest underlying emotional distress.',
    status: 'pending',
    priority: 'urgent',
    referredBy: 'Prof. James Torres',
  },
];
